/**
 * 图标统一从 TDesign Icons React 引入（ticon）。
 * 文档：https://tdesign.tencent.com/react/components/icon
 * 通过保持原有导出名，所有消费方无需修改 import 语句即可切换到 TDesign 图标。
 */
export {
  CalendarIcon,
  CalendarEventIcon as CalendarCheckIcon,
  ViewListIcon as ListIcon,
  ChartIcon,
  StarIcon,
  SearchIcon,
  NotificationIcon as BellIcon,
  MoonIcon,
  SunnyIcon as SunIcon,
  AddIcon as PlusIcon,
  CheckIcon,
  TimeIcon as ClockIcon,
  TagIcon,
  DeleteIcon as TrashIcon,
  ChevronDownIcon,
  MicrophoneIcon as MicIcon,
  QueueIcon as BatchIcon,
  RefreshIcon,
  UploadIcon,
  ImageIcon,
  LockOnIcon as LockIcon,
  HeartIcon,
  ChatIcon,
  ShareIcon as ShareIcon,
  UserIcon,
  UserCircleIcon,
  LocationIcon,
  FileIcon,
  BrowseIcon as EyeIcon,
  DashboardIcon,
  EditIcon,
  FlagIcon,
  SendIcon,
  ChevronRightIcon,
  MapLocationIcon as MapPinIcon,
  GiftIcon,
  UsergroupIcon as UsersIcon,
  SettingIcon,
  ToolsIcon,
  ChartBarIcon,
  CloseIcon,
  ViewModuleIcon as MenuIcon,
  FilterIcon,
  MoreIcon as DotsIcon,
} from 'tdesign-icons-react'
